name: Deploy
on: [push]
jobs:
  deploy_backend:
    name: deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          project_id: "architech-362918"
      - name: "deploy"
        run: |
          cd backend
          gcloud config get-value compute/region

          ls
          gcloud app deploy  --quiet
